const defaultData = {
  beat: false,
  beatFade: false,
  border: false,
  bounce: false,
  className: '',
  color: '',
  fade: false,
  fixedWidth: false,
  flip: undefined,
  icon: 'spinner',
  inverse: false,
  listItem: false,
  mask: undefined,
  maskId: '',
  pull: undefined,
  pulse: false,
  rotation: undefined,
  shake: false,
  size: undefined,
  spin: false,
  spinPulse: false,
  spinReverse: false,
  style: undefined,
  swapOpacity: false,
  symbol: undefined,
  tabIndex: 0,
  title: '',
  titleId: '',
  transform: '',
};

export default defaultData;
